eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8082
spring:
  application:
    name: wagesystem #表明该服务的名称
#启动springcloud的hystrix断路器
feign:
  hystrix:
    enabled: true